#!/usr/bin/env python3
"""Generate MoonBit copies of miniz's tdefl static tables.

The MoonBit compressor in `pdflite/flate` must agree with the vendored C byte
for byte, and these tables are the part of that agreement most likely to break
by hand: about 1,800 numbers whose individual values mean nothing to a reader,
so a transposed pair would survive review and later emit one wrong distance
code for one input.

Extracting them removes the copy. Rerun after changing the vendored miniz:

    python3 tools/miniz/gen_tdefl_tables.py

Refuses to write if a table is missing or the wrong length, since a short table
produces a compressor wrong only for rare inputs.
"""

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE = REPO / "pdflite" / "vendor" / "miniz" / "miniz.c"
TARGET = REPO / "pdflite" / "flate" / "pdf_tdefl_tables.mbt"

TABLES = [
    ("s_tdefl_len_sym", "tdefl_len_sym", 256),
    ("s_tdefl_len_extra", "tdefl_len_extra", 256),
    ("s_tdefl_small_dist_sym", "tdefl_small_dist_sym", 512),
    ("s_tdefl_small_dist_extra", "tdefl_small_dist_extra", 512),
    ("s_tdefl_large_dist_sym", "tdefl_large_dist_sym", 128),
    ("s_tdefl_large_dist_extra", "tdefl_large_dist_extra", 128),
    ("s_tdefl_packed_code_size_syms_swizzle", "tdefl_code_size_swizzle", 19),
]


def extract(source: str, symbol: str) -> list[int]:
    match = re.search(
        r"static const mz_uint(?:8|16)?\s+" + re.escape(symbol) + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\};",
        source,
        re.S,
    )
    if not match:
        sys.exit(f"table not found in miniz.c: {symbol}")
    return [int(v) for v in re.findall(r"-?\d+", match.group(1))]


def render(name: str, values: list[int]) -> str:
    rows = [
        "  " + ", ".join(str(v) for v in values[i : i + 16]) + ","
        for i in range(0, len(values), 16)
    ]
    return "///|\nlet {} : FixedArray[Int] = [\n{}\n]\n".format(name, "\n".join(rows))


def main() -> None:
    source = SOURCE.read_text()
    chunks = [
        "///|\n"
        "// Generated by tools/miniz/gen_tdefl_tables.py from\n"
        "// pdflite/vendor/miniz/miniz.c. Do not edit by hand.\n"
        "//\n"
        "// miniz's own tdefl tables, extracted rather than transcribed. The\n"
        "// compressor has to agree with the vendored C byte for byte, and 1,800\n"
        "// numbers that mean nothing individually are where a hand copy goes wrong\n"
        "// invisibly: a transposed pair passes review, then emits one wrong\n"
        "// distance code, for one input, much later.\n"
    ]
    total = 0
    for symbol, name, expected in TABLES:
        values = extract(source, symbol)
        if len(values) != expected:
            sys.exit(f"{symbol}: expected {expected} entries, found {len(values)}")
        total += len(values)
        chunks.append(render(name, values))
    TARGET.write_text("\n".join(chunks))
    print(f"wrote {TARGET.relative_to(REPO)} ({total} values across {len(TABLES)} tables)")


if __name__ == "__main__":
    main()
