//! Writes `../real_oracle_wbtest.mbt`: what pdf-writer (0.15.0, on ryu
//! 1.0.23) writes for `f32` operands, the reference of `format_real`.
//!
//!     cargo run --release --offline > ../real_oracle_wbtest.mbt
//!     (cd ../../.. && moon fmt)

use pdf_writer::Content;
use std::collections::BTreeSet;

/// What pdf-writer writes for one operand.
fn token(v: f32) -> String {
    let mut content = Content::new();
    content.move_to(v, 0.0);
    let bytes = content.finish().into_vec();
    let text = String::from_utf8(bytes).unwrap();
    text.strip_suffix(" 0 m").unwrap_or_else(|| panic!("{text:?}")).to_string()
}

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // splitmix64
        self.0 = self.0.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }
}

fn main() {
    let mut bits: BTreeSet<u32> = BTreeSet::new();
    // Every value, and the negative of every fifth.
    let mut count = 0u32;
    let mut add = |v: f32| {
        if v.is_finite() {
            bits.insert(v.to_bits());
            count += 1;
            if count % 5 == 0 {
                bits.insert((-v).to_bits());
            }
        }
    };
    let mut rng = Rng(0x5EED);

    // Special values and the limits of pdf-writer's cases: integers up to
    // the range of `i32`, ryu between 1e-6 and 1e12, `Display` beyond.
    for v in [
        0.0f32, 1.0, 0.5, 0.25, 0.1, 1.0 / 3.0, 2.0 / 3.0, 123.456789,
        f32::MIN_POSITIVE, f32::MAX, f32::EPSILON, 1e-6, 1e12, 1e-7, 1e13,
        2147483648.0, 2147483520.0, 4294967296.0, 3e9, 1e10, 16777216.0, 16777217.0,
        -2147483648.0, -4294967296.0, -1e10, -0.5, -1e-7, -1e13, -142.203125,
    ] {
        add(v);
        for d in 1..=3u32 {
            add(f32::from_bits(v.to_bits().wrapping_add(d)));
            add(f32::from_bits(v.to_bits().wrapping_sub(d)));
        }
    }
    for b in 1..=64u32 {
        add(f32::from_bits(b)); // subnormals
        add(f32::from_bits(0x0080_0000 - b));
    }
    // Powers of two and their neighbours: the interval of the values that
    // read back is asymmetric there.
    for e in -149..=127i32 {
        let v = 2.0f64.powi(e) as f32;
        add(v);
        for d in 1..=2u32 {
            add(f32::from_bits(v.to_bits().wrapping_add(d)));
            add(f32::from_bits(v.to_bits().wrapping_sub(d)));
        }
    }
    // Powers of ten and their neighbours.
    for e in -45..=38i32 {
        let v = format!("1e{e}").parse::<f32>().unwrap();
        add(v);
        for d in 1..=2u32 {
            add(f32::from_bits(v.to_bits().wrapping_add(d)));
            add(f32::from_bits(v.to_bits().wrapping_sub(d)));
        }
    }
    // Dyadic fractions: their decimal expansion ends in 5, so cutting it
    // right there is an exact tie (142.203125 is 142.20312, not 142.20313).
    for k in 1..=20u32 {
        let unit = 1.0f64 / (1u64 << k) as f64;
        for _ in 0..70 {
            let whole = (rng.next() % 2000) as f64;
            let odd = (rng.next() % (1u64 << k)) | 1;
            add((whole + odd as f64 * unit) as f32);
        }
    }
    // Every f32 with a tie at eight or nine digits between 100 and 1000:
    // the multiples of 2^-6 .. 2^-14 there, sampled.
    for _ in 0..700 {
        let k = 6 + (rng.next() % 9) as u32;
        let n = rng.next() % (1000u64 << k);
        add((n | 1) as f32 / (1u64 << k) as f32);
    }
    // Lengths as documents have them: hundredths, thirds, the engine's unit.
    for i in 0..260u32 {
        add(i as f32 * 0.01);
        add(i as f32 / 3.0);
        add(i as f32 / 127.0);
        add((i as f64 * 0.75) as f32);
        add((i as f64 * 0.1 + 0.05) as f32);
    }
    // Doubles rounded to f32, as an exporter passes them.
    for _ in 0..900 {
        let unit = (rng.next() >> 11) as f64 / (1u64 << 53) as f64;
        let scale = [1.0, 10.0, 600.0, 842.0, 1e4, 1e-3, 1e6][(rng.next() % 7) as usize];
        add((unit * scale) as f32);
    }
    // Random bit patterns.
    for _ in 0..1200 {
        add(f32::from_bits(rng.next() as u32));
    }

    println!("// Generated by `pdflite/export/oracle` (and `moon fmt`) from the pdf-writer");
    println!("// crate (0.15.0, with ryu 1.0.23): what it writes for an `f32` operand, by");
    println!("// the bits of the value. Do not edit.");
    println!();
    println!("///|");
    println!("let real_oracle_cases : ReadOnlyArray[(UInt, String)] = [");
    for b in &bits {
        println!("  (0x{:08X}U, \"{}\"),", b, token(f32::from_bits(*b)));
    }
    println!("]");
    eprintln!("{} cases", bits.len());
}
