#!/usr/bin/env python3
"""Corpus projection check (#434 PR 7): every vendored fixture's story
parts (main document, headers, footers, notes, comments) are joined,
read, segmented, projected, and field-classified inside a TRANSIENT
generated whitebox test; each part's TYPED outcome -- a refusal class,
or a compact shape signature on success -- must equal the committed
manifest, so a part can neither silently skip, silently change refusal
class, nor silently change structure.

Usage:
  python3 projection_check.py          # generate, run, clean up, verify
  python3 projection_check.py --update # regenerate the manifest
"""

import os
import re
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
FIXTURES = os.path.join(HERE, "fixtures")
MANIFEST = os.path.join(HERE, "projection_manifest.tsv")
GENERATED = os.path.join(
    REPO,
    "docx2html",
    "docx",
    "zz_corpus_projection_%d_wbtest.mbt" % os.getpid(),
)
# Story parts share the projection machinery; each present part is checked.
STORY_PART = re.compile(
    r"^word/(document|header\d*|footer\d*|footnotes|endnotes|comments)\.xml$"
)
# Recorded, never silent: giant stories exceed the embedded string-literal
# comfort zone of the transient test. Measured in ENCODED bytes.
OVERSIZE_BYTES = 2_000_000


def escape(text):
    out = []
    for ch in text:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif o == 10:
            out.append("\\n")
        elif o == 13:
            out.append("\\r")
        elif o == 9:
            out.append("\\t")
        elif o < 32 or o == 0x7F:
            out.append("\\u{%04x}" % o)
        else:
            out.append(ch)
    return "".join(out)


def collect_cases():
    """Returns [(label, xml_or_None, skip_reason_or_None)] in sorted order."""
    cases = []
    for name in sorted(os.listdir(FIXTURES)):
        if not name.endswith(".docx"):
            continue
        path = os.path.join(FIXTURES, name)
        try:
            with zipfile.ZipFile(path) as z:
                parts = sorted(p for p in z.namelist() if STORY_PART.match(p))
                if not parts:
                    cases.append((name + "::-", None, "no-story-parts"))
                    continue
                for part in parts:
                    label = name + "::" + part
                    data = z.read(part)
                    if len(data) > OVERSIZE_BYTES:
                        cases.append((label, None, "skipped:oversize"))
                        continue
                    try:
                        text = data.decode("utf-8")
                    except UnicodeDecodeError:
                        cases.append((label, None, "not-utf8"))
                        continue
                    cases.append((label, text, None))
        except zipfile.BadZipFile:
            cases.append((name + "::-", None, "not-a-zip"))
    return cases


def read_manifest():
    if not os.path.exists(MANIFEST):
        return ""
    with open(MANIFEST) as f:
        return f.read().rstrip("\n")


def generate(cases, expected):
    lines = []
    lines.append("// GENERATED by tests/corpus/projection_check.py -- transient,")
    lines.append("// never committed. Regenerate with the script.")
    lines.append("")
    lines.append("///|")
    lines.append('test "zz corpus fixtures project with pinned outcomes" {')
    lines.append("  let cases : Array[(String, String)] = [")
    for label, text, skip in cases:
        if skip is not None:
            continue
        lines.append('    ("%s", "%s"),' % (escape(label), escape(text)))
    lines.append("  ]")
    lines.append("  let skipped : Array[String] = [")
    for label, _, skip in cases:
        if skip is not None:
            lines.append('    "%s\\t%s",' % (escape(label), escape(skip)))
    lines.append("  ]")
    lines.append(
        """  fn sanitize(value : String) -> String {
    let out = StringBuilder()
    for ch in value {
      if ch == '\\n' || ch == '\\t' || ch == '\\r' {
        out.write_char(' ')
      } else {
        out.write_char(ch)
      }
    }
    out.to_string()
  }

  let outcomes : Array[String] = []
  for entry in skipped {
    outcomes.push(entry)
  }
  for case in cases {
    let (name, source) = case
    let outcome = try {
      match join_text_story(source) {
        Refused(StageRefused(stage~, cause~)) => {
          let label = match stage {
            StrictGate => "strict-gate"
            SourceScan => "source-scan"
            TolerantDom => "tolerant-dom"
          }
          let reason = match cause {
            InvalidXml(_) => "invalid-xml"
            Unsupported(_) => "unsupported"
            ResourceLimit(..) => "resource-limit"
            _ => "other"
          }
          "stage-refused:" + label + ":" + reason
        }
        Refused(ChildCountMismatch(..)) => "join-refused:child-count"
        Refused(NameMismatch(..)) => "join-refused:name"
        Refused(StructureMismatch(..)) => "join-refused:structure"
        Joined(story) => {
          // the production segmentation: the document body as one
          // segment, each accepted note or comment container as its own,
          // with part-wide continuous coordinates across segments
          match segment_joined_reader_story(
            "word/document.xml",
            story,
            empty_body_reader({ relationships: [] }),
          ) {
            SegmentationRefused(UnexpectedStoryRoot(..)) =>
              "segmentation-refused:unexpected-root"
            SegmentationRefused(MissingDocumentBody) =>
              "segmentation-refused:missing-body"
            SegmentationRefused(UnexpectedContainer(..)) =>
              "segmentation-refused:unexpected-container"
            SegmentedStory(output) =>
              match project_joined_reader_output(output) {
                ProjectionRefused(MissingSourceIdentity(..)) =>
                  "projection-refused:missing-source-identity"
                ProjectionRefused(SourceIdentityOutOfRange(_)) =>
                  "projection-refused:identity-out-of-range"
                ProjectionRefused(SourceShapeMismatch(..)) =>
                  "projection-refused:source-shape-mismatch"
                ProjectionRefused(UnownedVisibleContribution(..)) =>
                  "projection-refused:unowned-visible"
                Projected(projection) => {
                  classify_reader_projection_fields(projection)
                  let mut runs = 0
                  let mut text = 0
                  let mut nontext = 0
                  let mut transparent = 0
                  let mut suppressed = 0
                  let mut instruction = 0
                  let mut result = 0
                  let mut malformed = 0
                  let mut units = 0
                  for paragraph in projection.paragraphs {
                    runs = runs + paragraph.runs.length()
                    units = paragraph.projection_end
                    for contribution in paragraph.contributions {
                      match contribution.kind {
                        ProjectedText(_) => text = text + 1
                        VisibleNonText => nontext = nontext + 1
                        Transparent => transparent = transparent + 1
                        SuppressedContent => suppressed = suppressed + 1
                      }
                      match contribution.field_region {
                        OutsideField => ()
                        FieldInstruction => instruction = instruction + 1
                        FieldResult => result = result + 1
                        MalformedField => malformed = malformed + 1
                      }
                    }
                  }
                  "segments=\{output.segments.length()};paragraphs=\{projection.paragraphs.length()};runs=\{runs};text=\{text};nontext=\{nontext};transparent=\{transparent};suppressed=\{suppressed};units=\{units};carriers=\{projection.field_carriers.length()};fields=\{projection.field_index.fields.length()};regions=\{instruction}/\{result}/\{malformed};refusal_records=\{projection.field_index.refusals.length()}"
                }
              }
          }
        }
      }
    } catch {
      Unsupported(message~) => "error:Unsupported " + message
      ResourceLimit(message~, ..) => "error:ResourceLimit " + message
      InvalidXml(message~) => "error:InvalidXml " + message
      _ => "error:other"
    }
    outcomes.push(name + "\\t" + sanitize(outcome))
  }
  inspect(
    outcomes.join("\\n"),
    content=(
      #|%s
    ),
  )
}"""
        % "\n      #|".join(expected.split("\n"))
    )
    with open(GENERATED, "w") as f:
        f.write("\n".join(lines) + "\n")


def run_moon():
    return subprocess.run(
        [
            "moon",
            "test",
            "-p",
            "docx2html/docx",
            "--filter",
            "zz corpus fixtures project with pinned outcomes",
        ],
        cwd=os.path.join(REPO, "docx2html"),
        capture_output=True,
        text=True,
    )


def extract_actual(output):
    actual_lines = []
    in_diff = False
    for line in output.splitlines():
        if line.startswith("----"):
            in_diff = not in_diff
            continue
        if in_diff and line.startswith("+"):
            actual_lines.append(line[1:])
    return actual_lines


def main():
    update = "--update" in sys.argv
    cases = collect_cases()
    try:
        # update mode runs against an EMPTY expectation first: the inspect
        # diff of a nearly-correct manifest shows only changed hunks, which
        # would truncate the extracted outcomes
        generate(cases, "" if update else read_manifest())
        run = run_moon()
        output = run.stdout + run.stderr
        if run.returncode == 0:
            if update:
                print("manifest already up to date")
            print("corpus projection: OK (%d parts)" % len(cases))
            return 0
        if not update:
            for line in output.splitlines():
                if len(line) < 300:
                    print(line)
            print("corpus projection: FAILED (run --update to accept changes)")
            return 1
        actual_lines = extract_actual(output)
        if not actual_lines:
            for line in output.splitlines():
                if len(line) < 300:
                    print(line)
            print("corpus projection: could not extract outcomes")
            return 1
        # verify the fresh outcomes round-trip BEFORE touching the manifest
        candidate = "\n".join(actual_lines)
        generate(cases, candidate)
        rerun = run_moon()
        if rerun.returncode != 0:
            for line in (rerun.stdout + rerun.stderr).splitlines():
                if len(line) < 300:
                    print(line)
            print("corpus projection: outcomes do not round-trip; manifest untouched")
            return 1
        with open(MANIFEST + ".tmp", "w") as f:
            f.write(candidate + "\n")
        os.replace(MANIFEST + ".tmp", MANIFEST)
        print("manifest updated: %d entries" % len(actual_lines))
        print("corpus projection: OK (%d parts)" % len(cases))
        return 0
    finally:
        if os.path.exists(GENERATED):
            os.remove(GENERATED)


if __name__ == "__main__":
    sys.exit(main())
