#!/usr/bin/env python3
"""Corpus shadow check (#434 PR 5c): every vendored fixture's main story is
joined, read, projected, field-classified, and shadow-compared against the
legacy walker inside a TRANSIENT generated whitebox test; the per-fixture
outcome must equal the committed manifest, so a fixture can neither
silently skip nor silently change class.

Usage:
  python3 shadow_check.py          # generate, run, clean up, verify manifest
  python3 shadow_check.py --update # regenerate the manifest from actual outcomes
"""

import os
import re
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
FIXTURES = os.path.join(HERE, "fixtures")
MANIFEST = os.path.join(HERE, "shadow_manifest.tsv")
GENERATED = os.path.join(
    REPO, "docx2html", "docx", "zz_corpus_shadow_wbtest.mbt"
)


def escape(text):
    out = []
    for ch in text:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif o == 10:
            out.append("\\n")
        elif o == 13:
            out.append("\\r")
        elif o == 9:
            out.append("\\t")
        elif o < 32 or o == 0x7F:
            out.append("\\u{%04x}" % o)
        else:
            out.append(ch)
    return "".join(out)


def collect_cases():
    cases = []
    for name in sorted(os.listdir(FIXTURES)):
        if not name.endswith(".docx"):
            continue
        path = os.path.join(FIXTURES, name)
        try:
            with zipfile.ZipFile(path) as z:
                if "word/document.xml" not in z.namelist():
                    cases.append((name, None, "no-main-story"))
                    continue
                data = z.read("word/document.xml")
        except zipfile.BadZipFile:
            cases.append((name, None, "not-a-zip"))
            continue
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            cases.append((name, None, "not-utf8"))
            continue
        cases.append((name, text, None))
    return cases


def read_manifest():
    if not os.path.exists(MANIFEST):
        return ""
    with open(MANIFEST) as f:
        return f.read().rstrip("\n")


def generate(cases, expected):
    lines = []
    lines.append("// GENERATED by tests/corpus/shadow_check.py -- transient,")
    lines.append("// never committed. Regenerate with the script.")
    lines.append("")
    lines.append("///|")
    lines.append('test "zz corpus fixtures shadow the legacy walker" {')
    lines.append("  let cases : Array[(String, String)] = [")
    for name, text, skip in cases:
        if skip is not None:
            continue
        lines.append('    ("%s", "%s"),' % (name, escape(text)))
    lines.append("  ]")
    lines.append("  let outcomes : Array[String] = []")
    for name, _, skip in cases:
        if skip is not None:
            lines.append('  outcomes.push("%s\\t%s")' % (name, skip))
    lines.append(
        """  for case in cases {
    let (name, source) = case
    let outcome = try {
      match join_text_story(source) {
        Refused(StageRefused(stage~, ..)) => {
          let label = match stage {
            StrictGate => "strict-gate"
            SourceScan => "source-scan"
            TolerantDom => "tolerant-dom"
          }
          "stage-refused:" + label
        }
        Refused(_) => "join-refused"
        Joined(story) => {
          let node = story.root
          let children = match node.first("w:body") {
            Some(body) => body.element_children()
            None => node.element_children()
          }
          let items = empty_body_reader({ relationships: [] }).read_children(
            children,
          )
          match project_reader_items("word/document.xml", story.scan, items) {
            ProjectionRefused(refusal) =>
              "projection-refused:" + refusal.describe()
            Projected(projection) => {
              classify_reader_projection_fields(projection)
              let legacy = scan_reader_order_projection(
                "word/document.xml",
                @utf8.encode(source),
              )
              match compare_reader_projection_shadow(projection, legacy) {
                Some(difference) => "diverged: " + difference
                None => "shadowed"
              }
            }
          }
        }
      }
    } catch {
      Unsupported(message~) => "error:Unsupported " + message
      ResourceLimit(message~, ..) => "error:ResourceLimit " + message
      InvalidXml(message~) => "error:InvalidXml " + message
      _ => "error:other"
    }
    outcomes.push(name + "\\t" + outcome)
  }
  outcomes.sort()
  let expected =
    #|%s
  assert_eq(outcomes.join("\\n"), expected)
}"""
        % "\n    #|".join(expected.split("\n"))
    )
    with open(GENERATED, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    update = "--update" in sys.argv
    cases = collect_cases()
    expected = read_manifest()
    generate(cases, expected)
    try:
        run = subprocess.run(
            [
                "moon",
                "test",
                "-p",
                "docx2html/docx",
                "--filter",
                "zz corpus fixtures shadow the legacy walker",
            ],
            cwd=os.path.join(REPO, "docx2html"),
            capture_output=True,
            text=True,
        )
        output = run.stdout + run.stderr
        if update:
            match = re.search(
                r"^\+(.*?)(?=\n(?:-|\\ No newline|-{4}))",
                "",
            )
            # extract actual outcomes from the failure diff: lines starting
            # with '+' between the ---- markers
            actual_lines = []
            in_diff = False
            for line in output.splitlines():
                if line.startswith("----"):
                    in_diff = not in_diff
                    continue
                if in_diff and line.startswith("+"):
                    actual_lines.append(line[1:])
            if run.returncode == 0 and not actual_lines:
                print("manifest already up to date")
                return 0
            if actual_lines:
                with open(MANIFEST, "w") as f:
                    f.write("\n".join(actual_lines) + "\n")
                print("manifest updated: %d entries" % len(actual_lines))
                # re-run against the fresh manifest to confirm
                generate(cases, read_manifest())
                rerun = subprocess.run(
                    [
                        "moon",
                        "test",
                        "-p",
                        "docx2html/docx",
                        "--filter",
                        "zz corpus fixtures shadow the legacy walker",
                    ],
                    cwd=os.path.join(REPO, "docx2html"),
                    capture_output=True,
                    text=True,
                )
                if rerun.returncode != 0:
                    print(rerun.stdout + rerun.stderr)
                    print("corpus shadow: FAILED after manifest update")
                    return 1
                print("corpus shadow: OK (%d fixtures)" % len(cases))
                return 0
            print(output)
            print("corpus shadow: could not extract outcomes")
            return 1
        if run.returncode != 0:
            print(output)
            print("corpus shadow: FAILED (run --update to accept changes)")
            return 1
        print("corpus shadow: OK (%d fixtures)" % len(cases))
        return 0
    finally:
        if os.path.exists(GENERATED):
            os.remove(GENERATED)


if __name__ == "__main__":
    sys.exit(main())
