#!/usr/bin/env python3
"""Regenerate pagelayout/fonts' embedded font-metrics data.

The layout engine needs deterministic font metrics (advance widths, cmap,
vertical metrics) — not glyph outlines. This script strips each source font
down to its metric tables (head, hhea, maxp, hmtx, cmap, OS/2, post as
format 3), zlib-compresses the result, and emits MoonBit source files with
the compressed bytes as chunked `Bytes` literals, plus a manifest.

Outline data returns in a later milestone when the PDF backend embeds
fonts; the runtime API is designed so that swap changes no callers.

Sources (all SIL OFL 1.1; see pagelayout/fonts/LICENSES/):
  - Carlito (metric-compatible with Calibri)
      https://github.com/google/fonts/tree/main/ofl/carlito
  - Liberation Sans/Serif/Mono 2.1.5 (Arial/Times New Roman/Courier New)
      https://github.com/liberationfonts/liberation-fonts (release 2.1.5)
  - Noto Sans SC (CJK; variable font, default instance wght=400)
      https://github.com/google/fonts/tree/main/ofl/notosanssc

Usage:
  python3 -m venv venv && venv/bin/pip install fonttools
  venv/bin/python tools/font-metrics/gen_font_metrics.py <font-dir> <out-dir>

<font-dir> must contain the source TTFs named as in FACES below.
"""

import io
import sys
import zlib
from pathlib import Path

from fontTools.ttLib import TTFont

KEEP_TABLES = {"head", "hhea", "maxp", "hmtx", "cmap", "OS/2", "post"}
# 8KB of compressed payload per generated function: the escaped literal
# (4 chars/byte) must stay under the js backend's 65535-char text-segment
# limit (warning 0033).
CHUNK = 8 * 1024

# (moonbit identifier, source file, family exposed to the resolver, bold, italic)
FACES = [
    ("carlito_regular", "Carlito-Regular.ttf", "Carlito", False, False),
    ("carlito_bold", "Carlito-Bold.ttf", "Carlito", True, False),
    ("carlito_italic", "Carlito-Italic.ttf", "Carlito", False, True),
    ("carlito_bold_italic", "Carlito-BoldItalic.ttf", "Carlito", True, True),
    ("liberation_sans_regular", "LiberationSans-Regular.ttf", "Liberation Sans", False, False),
    ("liberation_sans_bold", "LiberationSans-Bold.ttf", "Liberation Sans", True, False),
    ("liberation_sans_italic", "LiberationSans-Italic.ttf", "Liberation Sans", False, True),
    ("liberation_sans_bold_italic", "LiberationSans-BoldItalic.ttf", "Liberation Sans", True, True),
    ("liberation_serif_regular", "LiberationSerif-Regular.ttf", "Liberation Serif", False, False),
    ("liberation_serif_bold", "LiberationSerif-Bold.ttf", "Liberation Serif", True, False),
    ("liberation_serif_italic", "LiberationSerif-Italic.ttf", "Liberation Serif", False, True),
    ("liberation_serif_bold_italic", "LiberationSerif-BoldItalic.ttf", "Liberation Serif", True, True),
    ("liberation_mono_regular", "LiberationMono-Regular.ttf", "Liberation Mono", False, False),
    ("liberation_mono_bold", "LiberationMono-Bold.ttf", "Liberation Mono", True, False),
    ("liberation_mono_italic", "LiberationMono-Italic.ttf", "Liberation Mono", False, True),
    ("liberation_mono_bold_italic", "LiberationMono-BoldItalic.ttf", "Liberation Mono", True, True),
    ("noto_sans_sc_regular", "NotoSansSC-VF.ttf", "Noto Sans SC", False, False),
]


def strip_to_metrics(path: Path) -> bytes:
    font = TTFont(str(path), lazy=False)
    # post format 3 drops glyph names — smallest valid post table.
    post = font["post"]
    post.formatType = 3.0
    post.glyphOrder = None
    for tag in [t for t in font.keys() if t != "GlyphOrder" and t not in KEEP_TABLES]:
        del font[tag]
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def mbt_bytes_literal(data: bytes) -> str:
    return "".join(f"\\x{b:02x}" for b in data)


def emit_face(out_dir: Path, ident: str, stripped: bytes) -> tuple[int, int]:
    compressed = zlib.compress(stripped, 9)
    chunks = [compressed[i : i + CHUNK] for i in range(0, len(compressed), CHUNK)]
    lines = [
        "///|",
        "// GENERATED by tools/font-metrics/gen_font_metrics.py — DO NOT EDIT.",
        "// zlib-compressed metrics-only sfnt (head/hhea/maxp/hmtx/cmap/OS\\/2/post).",
        "",
    ]
    for i, chunk in enumerate(chunks):
        lines.append("///|")
        lines.append(f"fn {ident}_chunk_{i}() -> Bytes {{")
        lines.append(f'  b"{mbt_bytes_literal(chunk)}"')
        lines.append("}")
        lines.append("")
    lines.append("///|")
    lines.append(f"fn {ident}_compressed() -> Array[Bytes] {{")
    lines.append(
        "  [" + ", ".join(f"{ident}_chunk_{i}()" for i in range(len(chunks))) + "]"
    )
    lines.append("}")
    lines.append("")
    (out_dir / f"data_{ident}.mbt").write_text("\n".join(lines))
    return len(stripped), len(compressed)


def main() -> None:
    font_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    registry_lines = [
        "///|",
        "// GENERATED by tools/font-metrics/gen_font_metrics.py — DO NOT EDIT.",
        "// Registry of every bundled face: (family, bold, italic, compressed sfnt).",
        "",
        "///|",
        "fn bundled_faces() -> Array[(String, Bool, Bool, Array[Bytes])] {",
        "  [",
    ]
    for ident, src, family, bold, italic in FACES:
        raw, comp = emit_face(out_dir, ident, strip_to_metrics(font_dir / src))
        print(f"{ident:32} stripped {raw:8} B  compressed {comp:8} B")
        registry_lines.append(
            f'    ("{family}", {str(bold).lower()}, {str(italic).lower()}, {ident}_compressed()),'
        )
    registry_lines += ["  ]", "}", ""]
    (out_dir / "data_registry.mbt").write_text("\n".join(registry_lines))


if __name__ == "__main__":
    main()
