#!/usr/bin/env python3
"""Regenerate pagelayout/fontoutlines' embedded glyph-outline data.

The PDF backend embeds a real font program so a reader needs nothing
installed to render the page. That is what makes CJK work at all: an
Identity-H composite font addresses glyphs by index *into the embedded
program*, so a substituted system font would draw the wrong glyphs
rather than a close-enough approximation.

This script strips each source font to the tables a PDF font program
needs (the metric tables plus `loca`/`glyf`), zlib-compresses it, and
armours the result as ASCII85 — pdflite already ships a tested
ASCII85 decoder, and at 1.25 source characters per byte it costs a
third of what MoonBit's `\\xNN` byte escapes would.

Outlines live in their own package, apart from the metrics in
`pagelayout/fonts`: layout needs metrics on every backend, but only the
PDF backend needs outlines, and an SVG-only build should not carry
several megabytes of glyf data.

Sources (all SIL OFL 1.1; see pagelayout/fonts/LICENSES/):
  - Noto Sans SC (CJK)
      https://github.com/google/fonts/tree/main/ofl/notosanssc

Usage:
  python3 -m venv venv && venv/bin/pip install fonttools
  venv/bin/python tools/font-metrics/gen_font_outlines.py <font-dir> <out-dir>
"""

import base64
import io
import sys
import zlib
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

# A PDF font program needs the metric tables plus the outlines themselves.
# Hinting (`cvt `/`fpgm`/`prep`) and layout (`GSUB`/`GPOS`) are dropped:
# this engine positions every glyph itself, so a reader never runs them.
KEEP_TABLES = {
    "head",
    "hhea",
    "maxp",
    "hmtx",
    "cmap",
    "OS/2",
    "post",
    "loca",
    "glyf",
}

# Compressed payload per generated function, in bytes. A multiple of 4 so
# every chunk but the last is a whole number of ASCII85 groups and decodes
# independently. 24576 B is 30720 ASCII85 characters, which stays well
# under the js backend's 65535-character text-segment limit (warning 0033)
# even after `"` and `\` are escaped.
CHUNK = 24576

# The largest generated literal the js backend accepts, with margin.
MAX_LITERAL_CHARS = 60000

# (moonbit identifier, source file, family, bold, italic, variable-font axes)
FACES = [
    (
        "noto_sans_sc_regular",
        "NotoSansSC-VF.ttf",
        "Noto Sans SC",
        False,
        False,
        # The fvar default is wght=100 (Thin), so the default master's
        # outlines are *not* the regular weight. Instancing pins the
        # weight text is actually laid out at.
        {"wght": 400},
    ),
]


def strip_to_outlines(path: Path, axes: dict | None) -> bytes:
    font = TTFont(str(path), lazy=False)
    # fontTools stamps head.modified with the wall clock on save, so
    # without this the same source font yields different bytes each run.
    font.recalcTimestamp = False
    if axes:
        font = instancer.instantiateVariableFont(
            font, axes, inplace=True, updateFontNames=False
        )
    # post format 3 drops glyph names — smallest valid post table, and a
    # PDF never looks glyphs up by name in a CIDFontType2.
    post = font["post"]
    post.formatType = 3.0
    post.glyphOrder = None
    for tag in [t for t in font.keys() if t != "GlyphOrder" and t not in KEEP_TABLES]:
        del font[tag]
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def mbt_ascii85_literal(chunk: bytes) -> str:
    """ASCII85 for pdflite's decoder: no `<~` frame, `~>` terminated.

    A leading `<~` would be read as two ASCII85 digits, since `<` is
    within the 33..117 digit range, so the Adobe frame must not appear.
    """
    armoured = base64.a85encode(chunk).decode("ascii") + "~>"
    # `"` and `\` are the only ASCII85 digits a MoonBit byte literal
    # cannot carry raw.
    return armoured.replace("\\", "\\x5c").replace('"', "\\x22")


def emit_face(out_dir: Path, ident: str, stripped: bytes) -> tuple[int, int]:
    compressed = zlib.compress(stripped, 9)
    chunks = [compressed[i : i + CHUNK] for i in range(0, len(compressed), CHUNK)]
    lines = [
        "///|",
        "// GENERATED by tools/font-metrics/gen_font_outlines.py — DO NOT EDIT.",
        "// zlib-compressed sfnt with glyph outlines, ASCII85-armoured.",
        "",
    ]
    for i, chunk in enumerate(chunks):
        literal = mbt_ascii85_literal(chunk)
        if len(literal) > MAX_LITERAL_CHARS:
            raise SystemExit(
                f"{ident} chunk {i}: {len(literal)} chars exceeds the "
                f"{MAX_LITERAL_CHARS}-char literal budget; lower CHUNK"
            )
        lines.append("///|")
        lines.append(f"fn {ident}_outline_chunk_{i}() -> Bytes {{")
        lines.append(f'  b"{literal}"')
        lines.append("}")
        lines.append("")
    lines.append("///|")
    lines.append(f"fn {ident}_outline_armoured() -> Array[Bytes] {{")
    lines.append(
        "  ["
        + ", ".join(f"{ident}_outline_chunk_{i}()" for i in range(len(chunks)))
        + "]"
    )
    lines.append("}")
    lines.append("")
    (out_dir / f"data_{ident}.mbt").write_text("\n".join(lines))
    return len(stripped), len(compressed)


def main() -> None:
    font_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    registry_lines = [
        "///|",
        "// GENERATED by tools/font-metrics/gen_font_outlines.py — DO NOT EDIT.",
        "// Registry of every bundled outline: (family, bold, italic, chunks).",
        "",
        "///|",
        "fn bundled_outlines() -> Array[(String, Bool, Bool, Array[Bytes])] {",
        "  [",
    ]
    for ident, src, family, bold, italic, axes in FACES:
        raw, comp = emit_face(out_dir, ident, strip_to_outlines(font_dir / src, axes))
        print(f"{ident:28} stripped {raw:9} B  compressed {comp:9} B")
        registry_lines.append(
            f'    ("{family}", {str(bold).lower()}, {str(italic).lower()}, '
            f"{ident}_outline_armoured()),"
        )
    registry_lines += ["  ]", "}", ""]
    (out_dir / "data_registry.mbt").write_text("\n".join(registry_lines))


if __name__ == "__main__":
    main()
